/*
 * This file is part of the Confirmate project.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
package de.fraunhofer.aisec.confirmate.queries.cra

import de.fraunhofer.aisec.cpg.TranslationResult
import de.fraunhofer.aisec.cpg.graph.Forward
import de.fraunhofer.aisec.cpg.graph.GraphToFollow
import de.fraunhofer.aisec.cpg.graph.Interprocedural
import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.allChildrenWithOverlays
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.Backup
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.DatabaseStorage
import de.fraunhofer.aisec.cpg.graph.concepts.file.WriteFile
import de.fraunhofer.aisec.cpg.query.May
import de.fraunhofer.aisec.cpg.query.QueryTree
import de.fraunhofer.aisec.cpg.query.allExtended
import de.fraunhofer.aisec.cpg.query.dataFlow

context(translationResult: TranslationResult)
fun relevantDataFlowToBackup(
    isRelevantData: (Node) -> Boolean = {
        it is DatabaseStorage ||
            translationResult
                .allChildrenWithOverlays<WriteFile> { write -> it == write.what }
                .isNotEmpty()
    }
): QueryTree<Boolean> {
    return translationResult.allExtended<Node>(sel = isRelevantData) { data ->
        // Find a data flow from the relevant data to a backup
        dataFlow(
            startNode = data,
            direction = Forward(GraphToFollow.DFG),
            type = May,
            scope = Interprocedural(),
            predicate = { it is Backup },
        )
    }
}
