/*
 * This file is part of the Confirmate project.
 */
package de.fraunhofer.aisec.confirmate.queries.cra

import de.fraunhofer.aisec.cpg.TranslationResult
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.AutomaticUpdates
import de.fraunhofer.aisec.cpg.query.*
import de.fraunhofer.aisec.cpg.query.GenericQueryOperators
import de.fraunhofer.aisec.cpg.query.QueryTree
import java.time.Duration

context(translationResult: TranslationResult)
fun updateIntervalSmallEnough(maxUpdateInterval: Duration): QueryTree<Boolean> {
    return translationResult.allExtended<AutomaticUpdates> {
        it.interval?.let { interval ->
            (interval.seconds le maxUpdateInterval.seconds).apply {
                stringRepresentation =
                    if (value) "The update interval is ${interval.seconds} seconds which is ok."
                    else
                        "The update interval is ${interval.seconds} seconds which is larger than the maximal accepted interval of ${maxUpdateInterval.seconds} seconds."
            }
        }
            ?: QueryTree(
                value = false,
                stringRepresentation = "Could not identify the update interval",
                node = it,
                operator = GenericQueryOperators.EVALUATE,
            )
    }
}
