/*
 * This file is part of the Confirmate project.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
package example.tagging

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.codeAndLocationFrom
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.LogLevel
import de.fraunhofer.aisec.cpg.graph.concepts.manualExtensions.LogWriteWithArguments
import de.fraunhofer.aisec.cpg.graph.concepts.manualExtensions.LoggingWithLevel
import de.fraunhofer.aisec.cpg.graph.evaluate
import de.fraunhofer.aisec.cpg.graph.statements.expressions.CallExpression
import de.fraunhofer.aisec.cpg.passes.concepts.TaggingContext
import de.fraunhofer.aisec.cpg.passes.concepts.each
import de.fraunhofer.aisec.cpg.passes.concepts.with

fun TaggingContext.tagLoggingGetLogger() {
    each<CallExpression>("logging.getLogger").with {
        node.overlays.filterIsInstance<LoggingWithLevel>().singleOrNull()
            ?: LoggingWithLevel(
                    logLevelThreshold = LogLevel.INFO,
                    enabled = true,
                    monitoringEnabled = false,
                    name = node.arguments.firstOrNull()?.evaluate() as? String,
                    retentionPeriod = null,
                    securityAlertsEnabled = false,
                    loggingService = null,
                    underlyingNode = node,
                )
                .apply {
                    this.codeAndLocationFrom(node)
                    this.name = Name(node.name.localName)
                }
    }
}


fun TaggingContext.tagLoggingInfo() {
    each<CallExpression>("logging.info").with {
        val log =
            node.overlays.filterIsInstance<LoggingWithLevel>().singleOrNull()
                ?: LoggingWithLevel(
                        logLevelThreshold = LogLevel.INFO,
                        enabled = true,
                        monitoringEnabled = false,
                        name = "logging",
                        retentionPeriod = null,
                        securityAlertsEnabled = false,
                        loggingService = null,
                        underlyingNode = null,
                    )
                    .apply {
                        this.codeAndLocationFrom(node)
                        this.name = Name("logging")
                    }

        LogWriteWithArguments(
                logArguments = node.arguments,
                logLevel = LogLevel.INFO,
                concept = log,
                underlyingNode = null,
            )
            .apply {
                this.codeAndLocationFrom(node)
                this.name = Name(node.name.localName)
            }
    }
}

fun TaggingContext.tagLogging() {
    tagLoggingGetLogger()
    tagLoggingInfo()
}
