/*
 * This file is part of the Confirmate project.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
package example.tagging

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.codeAndLocationFrom
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.DatabaseStorage
import de.fraunhofer.aisec.cpg.graph.concepts.manualExtensions.DatabaseQueryWithInput
import de.fraunhofer.aisec.cpg.graph.statements.expressions.MemberCallExpression
import de.fraunhofer.aisec.cpg.graph.statements.expressions.MemberExpression
import de.fraunhofer.aisec.cpg.passes.concepts.TaggingContext
import de.fraunhofer.aisec.cpg.passes.concepts.each
import de.fraunhofer.aisec.cpg.passes.concepts.with

/**
 * Tagging for Python SQLAlchemy database operations Tags db.session.add() calls as
 * DatabaseQueryWithInput
 */
fun TaggingContext.tagDatabaseAdd() {
    each<MemberCallExpression>(
        predicate = {
            it.name.localName == "add" &&
                    // Check if it's db.session.add(...)
                    (it.callee as? MemberExpression)?.base?.let { base ->
                        base is MemberExpression && base.name.localName == "session"
                    } == true
        }
    )
        .with {
            val dbStorage =
                object :
                    DatabaseStorage(
                        activityLogging = null,
                        atRestEncryption = null,
                        backups = mutableListOf(),
                        immutability = null,
                        resourceLogging = null,
                        internetAccessibleEndpoint = null,
                        geoLocation = null,
                        loggings = mutableListOf(),
                        redundancies = null,
                        usageStatistics = null,
                        creation_time = null,
                        description = "Database",
                        labels = null,
                        name = "database",
                        raw = null,
                        parent = null,
                        underlyingNode = node,
                    ) {}
                    .apply { this.codeAndLocationFrom(node) }

            DatabaseQueryWithInput(
                parameters =
                    node.arguments, // The objects being added to DB (e.g., new_password)
                modify = true, // This is a write operation
                calls = null,
                databaseService = null,
                storage = dbStorage,
                linkedConcept = dbStorage,
                underlyingNode = node,
            )
                .apply {
                    this.codeAndLocationFrom(node)
                    this.name = Name("db.session.add")
                }
        }
}

/** Main tagging function for Python database operations */
fun TaggingContext.tagPythonDatabase() {
    tagDatabaseAdd()
}
