/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins { id("buildlogic.kotlin-application-conventions") }

dependencies {
    api(libs.eclipse.cdt.core)
    api(libs.bundles.cpg) { isChanging = true }
    api(libs.jep)
}

application {
    // Define the main class for the application.
    mainClass = "de.fraunhofer.aisec.confirmate.AppKt"
}
