import org.gradle.accessors.dm.LibrariesForLibs

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
val libs = the<LibrariesForLibs>()  // necessary to be able to use the version catalog in buildSrc
